[package]
name = "rsa"
version = "1.0.1"
description = "An RSA library"
repository = "https://github.com/edjcase/motoko_rsa"
keywords = ["rsa", "cryptography", "encryption", "key", "private", "public"]
license = "MIT"

[dependencies]
base = "0.14.13"
new-base = "0.4.0"
base-x-encoder = "1.1.0"
itertools = "0.2.2"
asn1 = "2.0.2"
sha2 = "0.1.4"
xtended-numbers = "0.4.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"

[toolchain]
moc = "0.14.10"
